use std::time::Instant;

pub fn solve() {
    let start = Instant::now();

    /*
    Problem #2

    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

    */

    const TARGET: i32 = 4_000_000;
    let mut result: i32 = 0;

    let mut f1: i32 = 1;
    let mut f2: i32 = 1;

    loop {
        let current = f1 + f2;
        if current > TARGET {
            break;
        }

        if current % 2 == 0 {
            result += current;
        }

        f1 = f2;
        f2 = current;
    }

    let duration = start.elapsed();
    println!("problem_2: {}, time: {:?}", result, duration);
}
